### ISSUE TITLE
Make telemetry and caching configurable

### ISSUE THREAD

**Issue by kurthaegeman** [kurthaegeman/pre-commit-hooks-safety-pipenv#3]
To reduce the load on pyup.io, telemetry is disabled and caching is set to 1hr. This should be made configurable.

**Comment by Robbe-Haegeman** [comment]
Created proposal to solve this issue. (see #9)

This proposal also includes argument parsing tests, but doesn't verify if telemetry and caching work, since these should be tested in the used package (pipenv), not in the package using it
